library(tidyverse)
library(readxl)
# hdp <- read_excel("C:/Users/dldub/Downloads/hdp.xlsx")
hdp <- read.csv("hdp.csv")
View(hdp)
library(lme4)
library(lmerTest)
uncond0=lm(tumorsize ~ 1, data=hdp)
summary(uncond0)
uncond1=lmer(tumorsize ~ (1|DID), data=hdp)
summary(uncond1)
af=allFit(uncond1)
summary(af)
install.packages("reghelper")
library(reghelper)
ICC(uncond1)
comp01=anova(uncond1,uncond0)
comp01
l1pred=lmer(tumorsize ~ Sex + Age+ FamilyHx + LengthofStay + RBC + (1|DID), data=hdp)
summary(l1pred)
ICC(l1pred)
install.packages("lmmlasso")
library(lmmlasso)
install.packages("glmmLasso")
library(glmmLasso)
library(dplyr)
# hdp=mutate(DID$hdp=factor(DID$hdp))
hdp <- hdp %>% mutate(DID = factor(DID))
mutate(hdp,DID=factor(DID))
lastest=glmmLasso(fix=tumorsize ~ Sex + Age+ FamilyHx + LengthofStay + RBC ,  rnd=list(DID=~1), 
                  lambda=50, data=hdp)
summary(lastest)
install.packages("LMERConvenienceFunctions")
library(LMERConvenienceFunctions)
ffRanefLMER.fnc(model=l1pred,ran.effects=list(slopes=c("Sex", "Age", "FamilyHx", "LengthofStay"),
                                              by.vars="DID", corr=c(1,1,1,1)), 
                if.warn.not.add=FALSE, alpha=0.05)
l1pred2=lmer(tumorsize ~ Sex + Age+ FamilyHx + LengthofStay + (1+LengthofStay|DID), data=hdp)
test=allFit(l1pred2)
summary(test)
l1pred2=lmer(tumorsize ~ Sex + Age+ FamilyHx + LengthofStay + (1+LengthofStay|DID), data=hdp)
summary(l1pred2)
l2pred=lmer(tumorsize ~ Sex + Age+ FamilyHx + LengthofStay + Experience + School + 
              Lawsuits + (1+LengthofStayc|DID), data=hdp)
l2predrsnol2=lmer(tumorsize ~ Sex + Age+ FamilyHx + LengthofStay + 
              (1+LengthofStay|DID),REML=FALSE, data=hdp, control =lmerControl(optimizer = "bobyqa"))
summary(l2pred)
step(l2pred)
l2predrsnol2=lmer(tumorsize ~ Sex + Age+ FamilyHx + LengthofStay + (1+LengthofStay|DID),
                  REML=FALSE, data=hdp, control =
lmerControl(optimizer = "bobyqa"))
anova(l2predrs,l2predrsnol2)
library(redres)
shapiro.test(hdp$raw)
launch_redres(l2pred)
library(influence.ME)
infl <- influence(l2predrsnol2, obs = TRUE)
library(misty)
hdp$LengthofStaycgm <- center(hdp$LengthofStay, type = "CGM")
hdp$LengthofStaycwc <- center(hdp$LengthofStay, type = "CWC", cluster=hdp$DID)


## code for centering length of stay
hdp$LengthofStayc <- scale(hdp$LengthofStay, center=TRUE, scale=FALSE)
